Add catalan language
CasperVerswijvelt/TypeFast pull request #7
Opened 2020-12-02 22:53 UTC by guillemglez

Words from Thesaurus dictionary, Softcatalà
(GPL v2.1,  GPL v2 - https://github.com/Softcatala/catalan-dict-tools/)

Sentences from Josep Pla texts. Extracted from lletres.cat.

Flag asset from Wikimedia
https://commons.wikimedia.org/wiki/File:Flag_of_Catalonia.svg

2020-12-03 20:53 UTC, CasperVerswijvelt requested changes
Nice work! 
Due to the way the collapsable menus work in the preferences pane, the height for each group is hard-coded. Since you added a language it probably pushes off one of the toggles in the language settings. 

Height is set in `preferences.component.scss` at line 314
```
&.preferences-group-entries-language {
   max-height: 632px;
}
```

Increasing this with 31 px (height of 1 entry) should make it correct again

2020-12-03 20:53 UTC, CasperVerswijvelt commented on src/app/services/language.service.ts
> +        return 'cat';
Use 2 letter `ISO 639-1` code

2020-12-03 20:53 UTC, CasperVerswijvelt commented on src/styles.scss
> +.flag-icon-cat {
Use 2 letter `ISO 639-1` code

2020-12-03 20:53 UTC, CasperVerswijvelt commented on src/styles.scss
> +.flag-icon-cat {
Use 2 letter `ISO 639-1` code

2020-12-03 20:53 UTC, CasperVerswijvelt commented on src/app/services/language.service.ts
> +        return 'cat';
Use 2 letter `ISO 639-1` code

2020-12-03 20:53 UTC, CasperVerswijvelt commented on src/assets/languages/catalan/sentences.txt
> +En les evocacions, els biògrafs fan constar, recollint una tradició viva, que quan aquest, amb la tenora als llavis, tocava una sardana, «semblava que s'hi adormia...».
Are « and » characters typeable on catalan keyboards? If no maybe replace with regular quotation marks

2020-12-04 15:55 UTC, guillemglez commented on src/assets/languages/catalan/sentences.txt
> +En les evocacions, els biògrafs fan constar, recollint una tradició viva, que quan aquest, amb la tenora als llavis, tocava una sardana, «semblava que s'hi adormia...».
Ha! good catch!! Yes, it should be regular quotation marks :)

2020-12-04 16:40 UTC, merged